
/* GitHub Pages compatibility bridge.
   Preserves the original UI and replaces google.script.run with report-data.json. */
(function(){
  var FALLBACK_WEEKS=(function(){
    var out=[];
    var start=new Date('2026-06-01T00:00:00');
    for(var i=0;i<12;i++){
      var s=new Date(start); s.setDate(start.getDate()+i*7);
      var e=new Date(s); e.setDate(s.getDate()+6);
      function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
      out.push({week:i+1,startISO:iso(s),endISO:iso(e),goal:8000,actual:{gross_sales:0,discounts:0,returns:0,net_sales:0,gross_profit:0,total_orders:0,units:0,cogs:0,gross_margin:0}});
    }
    return out;
  })();

  function fallbackReport(reason){
    return {
      generated_at:new Date().toISOString(),
      config:{location_id:'67063775290',location_name:'Corro Trailer 1',order_tag:'HitsHudson',inclusion_rule:'Corro Trailer 1 warehouse/location OR HitsHudson; exclude Concierge/Employee without HitsHudson'},
      assumptions:{trailer:40000,setupFurniture:800,otherCapex:1321.62,capex:42121.62,marketingBudget:1000,discountReturnRate:0.15,grossMarginTarget:0.60,payrollWeekly:660,nicoleWeekly:660,hotelWeekly:1400,marketingActivationsTotal:638.33,marketingActivations:638.33,othersTotal:272,others:272,weeklyOpex:2060,oneTimeOpex:910.33,opex:2970.33},
      weeks:FALLBACK_WEEKS,
      orders:[],
      stats:{scanned:0,matched:0,excluded:0},
      warning:reason||'Fallback data loaded.'
    };
  }

  function loadReport(){
    return fetch('report-data.json?v='+Date.now(),{cache:'no-store'})
      .then(function(r){if(!r.ok)throw new Error('Could not load report-data.json ('+r.status+')');return r.json();})
      .then(function(r){
        if(!r||typeof r!=='object')return fallbackReport('Invalid report-data.json response.');
        if(!Array.isArray(r.weeks)||!r.weeks.some(function(w){return w&&w.startISO&&w.endISO;})){
          r.weeks=FALLBACK_WEEKS;
          r.warning='The published report had no valid weeks; repository fallback weeks were used.';
        }
        if(!Array.isArray(r.orders))r.orders=[];
        if(!r.stats)r.stats={scanned:0,matched:0,excluded:0};
        if(!r.assumptions)r.assumptions=fallbackReport().assumptions;
        return r;
      })
      .catch(function(err){console.error(err);return fallbackReport(err.message||String(err));});
  }

  function moneyRound(n){return Math.round(Number(n||0)*100)/100;}
  function emptySummary(){return {gross_sales:0,gross_profit:0,discounts:0,returns:0,net_sales:0,shipping_charges:0,taxes:0,total_sales:0,total_orders:0,units:0,cogs:0,gross_margin:0};}
  function normalizeOrder(o){
    o=o||{};var tags=Array.isArray(o.tags)?o.tags:(o.all_order_tags?String(o.all_order_tags).split(',').map(function(x){return x.trim();}).filter(Boolean):[]);
    return Object.assign({
      order_id:o.order_id||o.name||'',order_date:o.order_date||o.createdAt||'',
      order_tag:o.tag_has_hits?'HitsHudson':'Missing HitsHudson tag',all_order_tags:tags.length?tags.join(', '):'No tags',tag_has_hits:!!o.tag_has_hits,
      customer:o.customer||'N/A',customer_email:o.customer_email||'',payment_status:o.payment_status||'Unknown',financial_status:o.financial_status||o.payment_status||'Unknown',
      fulfillment_status:o.fulfillment_status||'Unknown',order_status:o.order_status||'Open',status_summary:o.status_summary||'',refund_status:o.refund_status||'No Refund',
      delivery_method:o.delivery_method||'IN STORE',is_in_store:o.is_in_store!==false,location:o.location||'Corro Trailer 1',location_matches_hits:o.location_matches_hits!==undefined?!!o.location_matches_hits:String(o.location||'').toLowerCase().indexOf('corro trailer 1')>=0,location_evidence:o.location_evidence||o.location||'',
      source_name:o.source_name||'',app_name:o.app_name||'',source_display:o.source_display||'Generated by GitHub Actions',line_count:Number(o.line_count||0)
    },o);
  }
  function aggregateOrders(orders){
    var s=emptySummary();
    (orders||[]).forEach(function(o){['gross_sales','gross_profit','discounts','returns','net_sales','shipping_charges','taxes','total_sales','units','cogs'].forEach(function(k){s[k]+=Number(o[k]||0);});s.total_orders+=1;});
    Object.keys(s).forEach(function(k){if(k!=='gross_margin'&&k!=='total_orders'&&k!=='units')s[k]=moneyRound(s[k]);});
    s.gross_margin=s.net_sales>0?s.gross_profit/s.net_sales:0;return s;
  }
  function validWeeks(r){return (r&&Array.isArray(r.weeks)?r.weeks:[]).filter(function(w){return w&&w.startISO&&w.endISO;});}
  function weekOptions(r){return validWeeks(r).map(function(w){return {label:'Week '+w.week+' · '+w.startISO+' – '+w.endISO+' · Goal $'+Math.round(w.goal||0).toLocaleString(),startISO:w.startISO,endISO:w.endISO,week:w.week,goal:Number(w.goal||0),include_in_calculation:w.include_in_calculation!==false,source:'Repository report-data.json'};});}
  function monthOptions(r){
    var m={};validWeeks(r).forEach(function(w){var d=new Date(w.startISO+'T00:00:00');var key=d.getFullYear()+':'+(d.getMonth()+1);if(!m[key])m[key]={year:d.getFullYear(),month:d.getMonth()+1,goal:0,weeks:[]};m[key].goal+=Number(w.goal||0);m[key].weeks.push(w.week);});
    return Object.keys(m).sort(function(a,b){var aa=a.split(':').map(Number),bb=b.split(':').map(Number);return aa[0]-bb[0]||aa[1]-bb[1];}).map(function(k){var x=m[k];x.value=k;x.label=new Date(x.year,x.month-1,1).toLocaleString('en-US',{month:'long',year:'numeric'})+' · Goal $'+Math.round(x.goal).toLocaleString();return x;});
  }
  function rangeData(r,p){
    p=p||{};var start,end,label;
    if(p.cumulative){var cvw=validWeeks(r);start=cvw[0].startISO;var today=new Date();var todayISO=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');end=todayISO<cvw[cvw.length-1].endISO?todayISO:cvw[cvw.length-1].endISO;label='Cumulative · Since HITS started';}
    else if(p.startISO&&p.endISO){start=p.startISO;end=p.endISO;label=p.label||start+' – '+end;}
    else if(p.month){start=p.year+'-'+String(p.month).padStart(2,'0')+'-01';var d=new Date(Number(p.year),Number(p.month),0);end=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');label=d.toLocaleString('en-US',{month:'long',year:'numeric'});}
    else{var vw=validWeeks(r);start=vw[0].startISO;end=vw[vw.length-1].endISO;label='Project';}
    var orders=(r.orders||[]).map(normalizeOrder).filter(function(o){var day=String(o.order_date||'').slice(0,10);var tags=String(o.all_order_tags||'').toLowerCase();var clearlyNonHits=!o.tag_has_hits&&(tags.indexOf('employee')>=0||tags.indexOf('concierge')>=0);var qualifies=!clearlyNonHits&&(!!o.tag_has_hits||!!o.location_matches_hits);return qualifies&&day&&day>=start&&day<=end;});
    var matchingWeeks=validWeeks(r).filter(function(w){return w.endISO>=start&&w.startISO<=end;});
    return {ok:true,generated:r.generated_at,period_label:label,summary:aggregateOrders(orders),orders:orders,lines:Array.isArray(r.lines)?r.lines:[],stats:{total_orders_scanned:Number((r.stats||{}).scanned||0),matched_orders:orders.length,matched_lines:Number((r.stats||{}).matched_lines||0),online_orders_skipped:0,unknown_source_orders:0,location_skipped:Number((r.stats||{}).excluded||0),excluded_missing_tag:Number((r.stats||{}).excluded_missing_tag||0),excluded_wrong_location:Number((r.stats||{}).excluded_wrong_location||0),excluded_non_hits_tag:Number((r.stats||{}).excluded_non_hits_tag||0),orders_with_hits_tag:orders.filter(function(o){return o.tag_has_hits;}).length,tag_only_orders:orders.filter(function(o){return o.tag_has_hits&&!o.location_matches_hits;}).length,orders_missing_hits_tag:orders.filter(function(o){return !o.tag_has_hits;}).length},goal_context:{source:'Repository report-data.json',type:p.cumulative?'cumulative':(p.month?'month':'week'),week:matchingWeeks.length===1?matchingWeeks[0].week:'',startISO:start,endISO:end,goal:matchingWeeks.reduce(function(a,w){return a+Number(w.goal||0);},0),weeks:matchingWeeks}};
  }
  function projectData(r){
    var a=r.assumptions||{};var vw=validWeeks(r);
    return {ok:true,generated:r.generated_at,period_label:vw[0].startISO+' – '+vw[vw.length-1].endISO,weeks:vw.map(function(w){return Object.assign({include_in_calculation:w.include_in_calculation!==false,actual:emptySummary()},w);}),assumptions:{weeks:vw.length,calculation_weeks:vw.filter(function(w){return w.include_in_calculation!==false;}).length,calculation_start_week:1,capex:Number(a.capex||42121.62),trailer_cost:Number(a.trailer||40000),setup_furniture_cost:Number(a.setupFurniture||800),capex_other_costs:Number(a.otherCapex||1321.62),weekly_gross_sales_budget:Number((vw[0]&&vw[0].goal)||8000),weekly_marketing_income_budget:Number(a.marketingBudget||1000),discounts_returns_rate:Number(a.discountReturnRate||0.15),gross_margin_target:Number(a.grossMarginTarget||0.60),payroll_weekly_cost:Number(a.payrollWeekly||a.nicoleWeekly||660),nicole_weekly_cost:Number(a.payrollWeekly||a.nicoleWeekly||660),hotel_weekly:Number(a.hotelWeekly||1400),marketing_activations_total:Number(a.marketingActivationsTotal||a.marketingActivations||638.33),marketing_activations:Number(a.marketingActivationsTotal||a.marketingActivations||638.33),others_total:Number(a.othersTotal||a.others||272),others:Number(a.othersTotal||a.others||272),weekly_opex_budget:Number(a.weeklyOpex||2060),one_time_opex:Number(a.oneTimeOpex||910.33),total_project_opex:Number(a.opex||2970.33),weekly_net_sales_budget:Number((vw[0]&&vw[0].goal)||8000)*(1-Number(a.discountReturnRate||0.15)),goals_source:'Repository report-data.json'},stats:{matched_orders:Number((r.stats||{}).matched||0),orders_missing_hits_tag:Number((r.stats||{}).orders_missing_hits_tag||0)}};
  }
  function runner(){
    var ok=function(){},fail=function(e){console.error(e);};
    var api={withSuccessHandler:function(fn){ok=fn||ok;return api;},withFailureHandler:function(fn){fail=fn||fail;return api;}};
    ['getWeekOptions','getMonthOptions','getHitsData','getHitsProjectData'].forEach(function(name){api[name]=function(arg){loadReport().then(function(r){if(name==='getWeekOptions')ok(weekOptions(r));else if(name==='getMonthOptions')ok(monthOptions(r));else if(name==='getHitsData')ok(rangeData(r,arg));else ok(projectData(r));}).catch(fail);};});
    return api;
  }
  window.google=window.google||{};window.google.script=window.google.script||{};Object.defineProperty(window.google.script,'run',{configurable:true,get:runner});
})();
